version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    rebase-strategy: "auto"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      rust-direct:
        dependency-type: "production"
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "rust"
    rebase-strategy: "auto"
