[workspace]
pr_draft = false
release_always = false
publish = false
git_tag_enable = false
git_release_enable = false
semver_check = true

[[package]]
name = "guisu"
git_tag_enable = true
# GitHub Release is created by cargo-dist
git_release_enable = false
git_tag_name = "v{{ version }}"
semver_check = false

[changelog]
commit_preprocessors = []
protect_breaking_commits = true
