[package]
name = "guisu-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "CLI for guisu dotfile manager"

[[bin]]
name = "guisu"
path = "src/main.rs"

[lib]
name = "guisu"

[dependencies]
guisu-config = { path = "../config" }
guisu-core = { path = "../core", features = ["anyhow"] }
guisu-crypto = { path = "../crypto" }
guisu-engine = { path = "../engine" }
guisu-template = { path = "../template" }

anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
comfy-table.workspace = true
crossterm.workspace = true
dialoguer.workspace = true
dirs.workspace = true
git2.workspace = true
git2_credentials.workspace = true
hex.workspace = true
indexmap.workspace = true
indicatif.workspace = true
libc.workspace = true
lscolors.workspace = true
miette.workspace = true
os_info.workspace = true
rayon.workspace = true
nu-ansi-term.workspace = true
owo-colors.workspace = true
ratatui.workspace = true
rustix.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
similar.workspace = true
subtle.workspace = true
tempfile.workspace = true
thiserror.workspace = true
terminal_size.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
walkdir.workspace = true
xdg.workspace = true

[build-dependencies]
anyhow.workspace = true
vergen.workspace = true
vergen-git2.workspace = true

[lints]
workspace = true

[package.metadata.dist]
formula = "guisu"
