[book]
title = "Guisu"
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "light"
preferred-dark-theme = "dark"
git-repository-url = "https://github.com/YvanY0/guisu"
edit-url-template = "https://github.com/YvanY0/guisu/edit/main/docs/{path}"
additional-css = ["theme/nord.css"]
